"""empty message

Revision ID: 107ded779dd5
Revises: 733c2cf3a632
Create Date: 2018-05-20 21:19:44.431000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '107ded779dd5'
down_revision = '733c2cf3a632'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('create_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'create_time')
    # ### end Alembic commands ###
